export type ThemeColor =
  | 'black_1'
  | 'black_2'
  | 'black_3'
  | 'black_4'
  | 'white_1'
  | 'white_2'
  | 'white_3'
  | 'white_4'
  | 'white_5'
  | 'violet_1'
  | 'violet_2'
  | 'violet_3'
  | 'violet_4'
  | 'violet_5'
  | 'red_1'
  | 'red_2'
  | 'red_3'
  | 'red_4'
  | 'red_5'
  | 'green_1'
  | 'green_2'
  | 'green_3'
  | 'green_4'
  | 'green_5'
  | 'yellow_1'
  | 'yellow_2'
  | 'yellow_3'
  | 'yellow_4'
  | 'yellow_5'
  | 'blue_1'
  | 'blue_2'
  | 'blue_3'
  | 'blue_4'
  | 'blue_5';

export type ThemeColorMap = { [K in ThemeColor]: string };

export type Theme = ThemeColorMap;
